### ISSUE TITLE
原来项目里面的windows form相关的为什么要干掉

### ISSUE THREAD

**Issue by furacas** [Pik-4/Hearthstone_Mercenaries_BepInEx#1]

**Comment by Pik-4** [comment]
1. 用BepInExConfigManager接管了所有设置，再单独一个窗口意义不大
2. 带Windows Form编译一直报错，懒得修了

**Comment by furacas** [comment]
其实我遇到了个类似的问题，本来想问问 Windows Form怎么处理的。。。
但是编译应该不会报错的。只是运行的时候会报错

**Comment by Pik-4** [comment]
编译需要找依赖的dll，理论上只要能编译通过，然后把相关的dll放到unstripped_corlib就能解决运行报错..
