### ISSUE TITLE
蓝色传送门typeid=0

### ISSUE THREAD

**Issue by z-henry** [Pik-4/Hearthstone_Mercenaries_BepInEx#3]
你好，我在学习规划路径部分代码的时候发现，会有一个判断蓝色传送门的操作                   
`if (donelist[min][i].NodeTypeId == 0)   //蓝色传送门后面到BOSS前全部设置为完成状态`
神秘节点的取值是0,14,18,19,23,44
我测试0是未揭示的神秘节点，18才是传送门，而且从0变成18的过程成会体现在下一次HandleMap中
不知道我调试的对不对，希望交流一下！

**Comment by Pik-4** [comment]
这部分代码是原作者的，我分析的是HandleMap选择节点，getshenmi规划路径；handlemap在每次地图加载时调用，getshenmi在handlemap中调用。关于蓝色传送门，我认为是在激活神秘节点后才更新。（当然不排除我分析错了，另外程序异常时会重进地图刷新路径）

**Comment by z-henry** [comment]
好的谢谢
