### ISSUE TITLE
关于“TryAutoNextSelectCoin”函数的补丁

### ISSUE THREAD

**Issue by z-henry** [Pik-4/Hearthstone_Mercenaries_BepInEx#4]
`TryAutoNextSelectCoin`对应的补丁函数中，会调用`Network.Get().ChooseLettuceMapNode(minNode[i].NodeId)`来选择非怪物节点。

但是我测试发现，当出现多个非怪物节点连续的时候，将会一瞬间调用多次`Network.Get().ChooseLettuceMapNode(minNode[i].NodeId)`，这会导致`TryAutoNextSelectCoin`短时间内的再次调用。并且其中的`NetCache.Get().GetNetObject<NetCache.NetCacheLettuceMap>()`并不能将预期的地图情况下载下来（可能只来得及响应其中前一两次的节点选择），最终可能导致对同一怪物节点的两次`GameMgr.Get().FindGame`，造成游戏崩溃。

我能想到的方法就是在`Network.Get().ChooseLettuceMapNode(minNode[i].NodeId)`后加上sleep，但是这会导致UI线程卡住，
另一个就是找到一种更新NetCache的方法，很遗憾我没有找到

希望能与你交流一下

**Comment by Pik-4** [comment]
这是因为`Network.RegisterNetHandler`导致结果异步接收...目前我也没啥很好的解决办法。可能重新找个方法Patch进去，或者在Update里面重新写一个节点选择会更好。如果不考虑代码执行效率，你还可以试试在选择完节点后重新进入佣兵模式。

**Comment by z-henry** [comment]
感谢你的讲解
我不会找可以patch的方法，所以可能需要尝试对update中的map场景进行处理
